# Generated by Django 5.2.7 on 2025-10-04 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('central', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Almacen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej. Almacén Principal, Tienda 1, Bodega de Devoluciones.', max_length=100, unique=True, verbose_name='Nombre del Almacén')),
                ('codigo', models.CharField(max_length=10, unique=True, verbose_name='Código de Almacén')),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Almacén',
                'verbose_name_plural': 'Almacenes',
            },
        ),
        migrations.CreateModel(
            name='MovimientoInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('tipo_movimiento', models.CharField(choices=[('E', 'Entrada (Compra/Ajuste Positivo)'), ('S', 'Salida (Venta/Ajuste Negativo)')], max_length=1, verbose_name='Tipo de Movimiento')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cantidad Movida')),
                ('referencia_doc', models.CharField(help_text='Ej. Número de Factura, Orden de Compra.', max_length=100, verbose_name='Referencia de Documento')),
                ('almacen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.almacen', verbose_name='Almacén de Origen/Destino')),
                ('asiento_contable_nucleo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='central.transaccionencabezado', verbose_name='Asiento Contable Relacionado')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='central.producto', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Movimiento de Inventario',
                'verbose_name_plural': 'Movimientos de Inventario',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Cantidad en Stock')),
                ('almacen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.almacen', verbose_name='Almacén')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='central.producto', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Stock',
                'verbose_name_plural': 'Existencias de Stock',
                'ordering': ['producto__nombre'],
                'unique_together': {('producto', 'almacen')},
            },
        ),
    ]
