# Generated by Django 5.2.7 on 2025-10-06 17:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('central', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PeriodoNomina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=100, verbose_name='Descripción del Período')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de Inicio')),
                ('fecha_fin', models.DateField(verbose_name='Fecha de Fin')),
                ('fecha_pago', models.DateField(verbose_name='Fecha de Pago')),
                ('estado', models.CharField(choices=[('A', 'Abierto'), ('C', 'Cerrado'), ('P', 'Procesado')], default='A', max_length=1, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Período de Nómina',
                'verbose_name_plural': 'Períodos de Nómina',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='ConceptoNomina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10, unique=True, verbose_name='Código del Concepto')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Concepto')),
                ('tipo', models.CharField(choices=[('D', 'Devengo (Ingreso)'), ('C', 'Deducción (Descuento)')], max_length=1, verbose_name='Tipo de Concepto')),
                ('naturaleza', models.CharField(choices=[('F', 'Fijo'), ('V', 'Variable')], max_length=1, verbose_name='Naturaleza')),
                ('valor_fijo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor Fijo')),
                ('porcentaje', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Porcentaje')),
                ('base_calculo', models.CharField(blank=True, help_text='Ej: SALARIO_BASE, TOTAL_DEVENGOS', max_length=50, verbose_name='Base de Cálculo')),
                ('cuenta_contable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='central.cuentacontable', verbose_name='Cuenta Contable')),
            ],
            options={
                'verbose_name': 'Concepto de Nómina',
                'verbose_name_plural': 'Conceptos de Nómina',
            },
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(max_length=20, unique=True, verbose_name='Cédula/Pasaporte')),
                ('nombres', models.CharField(max_length=100, verbose_name='Nombres')),
                ('apellidos', models.CharField(max_length=100, verbose_name='Apellidos')),
                ('fecha_ingreso', models.DateField(verbose_name='Fecha de Ingreso')),
                ('puesto', models.CharField(max_length=100, verbose_name='Puesto de Trabajo')),
                ('departamento', models.CharField(max_length=100, verbose_name='Departamento')),
                ('tipo_contrato', models.CharField(choices=[('F', 'Tiempo Fijo'), ('I', 'Indefinido'), ('O', 'Por Obra/Labor')], max_length=1, verbose_name='Tipo de Contrato')),
                ('salario_base', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Salario Base Mensual')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('usuario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario del Sistema')),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
                'ordering': ['apellidos', 'nombres'],
            },
        ),
        migrations.CreateModel(
            name='NominaEncabezado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_devengos', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total Devengos')),
                ('total_deducciones', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total Deducciones')),
                ('neto_a_pagar', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Neto a Pagar')),
                ('asiento_contable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='central.transaccionencabezado', verbose_name='Asiento Contable')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nomina.empleado', verbose_name='Empleado')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nomina.periodonomina', verbose_name='Período de Nómina')),
            ],
            options={
                'verbose_name': 'Nómina',
                'verbose_name_plural': 'Nóminas',
                'unique_together': {('empleado', 'periodo')},
            },
        ),
        migrations.CreateModel(
            name='NominaDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='Cantidad')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor')),
                ('concepto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nomina.conceptonomina', verbose_name='Concepto')),
                ('nomina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='nomina.nominaencabezado', verbose_name='Nómina')),
            ],
            options={
                'verbose_name': 'Detalle de Nómina',
                'verbose_name_plural': 'Detalles de Nómina',
            },
        ),
    ]
