# Generated by Django 5.2.7 on 2025-10-06 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReporteConfiguracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre descriptivo del reporte', max_length=100, verbose_name='Nombre del Reporte')),
                ('tipo_reporte', models.CharField(choices=[('INV', 'Inventario'), ('VEN', 'Ventas'), ('COM', 'Compras'), ('NOM', 'Nómina'), ('CON', 'Contabilidad')], max_length=3, verbose_name='Tipo de Reporte')),
                ('codigo', models.CharField(max_length=20, unique=True, verbose_name='Código del Reporte')),
                ('activo', models.BooleanField(default=True)),
                ('configuracion_json', models.JSONField(default=dict, help_text='Parámetros y configuración específica del reporte', verbose_name='Configuración JSON')),
            ],
            options={
                'verbose_name': 'Configuración de Reporte',
                'verbose_name_plural': 'Configuraciones de Reportes',
            },
        ),
    ]
