# Generated by Django 5.2.7 on 2025-10-06 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('central', '0001_initial'),
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_orden', models.CharField(help_text='Número consecutivo único de orden de compra.', max_length=20, unique=True, verbose_name='Número de Orden')),
                ('fecha_emision', models.DateField(verbose_name='Fecha de Emisión')),
                ('fecha_esperada', models.DateField(verbose_name='Fecha Esperada de Entrega')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Subtotal')),
                ('impuesto', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Impuesto')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total')),
                ('estado', models.CharField(choices=[('B', 'Borrador'), ('E', 'Emitida'), ('R', 'Recibida Parcialmente'), ('C', 'Completada'), ('A', 'Anulada')], default='B', max_length=1, verbose_name='Estado')),
                ('moneda', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='central.moneda', verbose_name='Moneda')),
                ('proveedor', models.ForeignKey(limit_choices_to={'tipo__in': ['P', 'A']}, on_delete=django.db.models.deletion.PROTECT, to='central.entidadcomercial', verbose_name='Proveedor')),
            ],
            options={
                'verbose_name': 'Orden de Compra',
                'verbose_name_plural': 'Órdenes de Compra',
                'ordering': ['-fecha_emision', 'numero_orden'],
            },
        ),
        migrations.CreateModel(
            name='OrdenCompraDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_solicitada', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cantidad Solicitada')),
                ('cantidad_recibida', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Cantidad Recibida')),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio Unitario')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Subtotal Línea')),
                ('orden_compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='compras.ordencompra', verbose_name='Orden de Compra')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='central.producto', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Detalle de Orden de Compra',
                'verbose_name_plural': 'Detalles de Orden de Compra',
            },
        ),
        migrations.CreateModel(
            name='RecepcionCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_recepcion', models.DateField(verbose_name='Fecha de Recepción')),
                ('referencia', models.CharField(max_length=50, verbose_name='Referencia/Número de Recepción')),
                ('movimiento_inventario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.movimientoinventario', verbose_name='Movimiento de Inventario Relacionado')),
                ('orden_compra', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recepciones', to='compras.ordencompra', verbose_name='Orden de Compra')),
            ],
            options={
                'verbose_name': 'Recepción de Compra',
                'verbose_name_plural': 'Recepciones de Compra',
                'ordering': ['-fecha_recepcion'],
            },
        ),
    ]
